### ISSUE TITLE
Compile under windows 

### ISSUE THREAD

**Issue by pwnmactep** [aczid/esp8266_upc_keys#1]
Hello,

can u help me to run / compile this code under windows ? I

I Downloaded https://github.com/boseji/ESP8266-uof-windows-sdk-portable

Is it possbile to comp. this code with the SDK i Downloaded

**Comment by aczid** [comment]
I have no idea. Good luck!

**Comment by pwnmactep** [comment]
Hi ,

Ok . Would you be so Nice an Could you send me the two Compiled bin Files ?

**Comment by pwnmactep** [comment]
Pwnmactep@gmail.com

Von meinem iPhone gesendet

**Comment by aczid** [comment]
I've added the binary to the repo. Now you just need esptool.

**Comment by pwnmactep** [comment]
Ty man
