### ISSUE TITLE
Read/Get Saved Passwords

### ISSUE THREAD

**Issue by pwnmactep** [aczid/esp8266_upc_keys#2]
Hello,

somehow i cant save the Passwords to the Flash. (User Flash Area is full)

Device : esp8266-12-e

I did  :

python esptool.py  --port COM4  erase_flash 

python esptool.py  --port COM4  write_flash 0 esp8266_upc_keys-0x00000.bin 0x40000 esp8266_upc_keys-0x40000.bin 0x3c000 saved_passwords.bin

...Let it Get my Password...

python esptool.py  --port COM4 read_flash 0x3c000 0x4000 saved_passwords.bin

Should the saved_passwords.bin had to been formated in a Special way ?
what does this Command mean in your Makefile :

saved_passwords.bin:
	perl -e 'print "\xff"x0x4000' > $@

**Comment by aczid** [comment]
This command fills the saved_passwords.bin file with all 0xff bytes. This formatting is checked by the code. Therefore, for the first time flashing, you need to also flash this 0x4000 bytes file of all 0xff's. If that area is not set to all 0xff's, the code will complain that the saved passwords area is full. This area is also saved to / loaded from the file when (re)flashing.

**Comment by pwnmactep** [comment]
First i heave to  : 
- perl -e 'print "\xff"x0x4000' > saved_passwords.bin


Can you check the File Please ? : https://www.dropbox.com/s/i0q3fizch2wjeo5/saved_passwords.bin?dl=0

then : 

- python esptool.py --port COM4 erase_flash
- python esptool.py --port COM4 write_flash 0 esp8266_upc_keys-0x00000.bin 0x40000 esp8266_upc_keys-0x40000.bin 0x3c000 saved_passwords.bin ?

Right `?

**Comment by aczid** [comment]
Yep looks fine!

**Comment by pwnmactep** [comment]
Hi,

Some how i still get the error "user flash area is full "

Maybe i need a special firmware ?
My Device is : http://www.exp-tech.de/nodemcu-v2-lua-based-esp8266?gclid=CKSS05vf9dACFQ5sGwod0GwOog

Sorry for stress you..hope u got a idea..

**Comment by aczid** [comment]
Seems like you may have still uploaded it to the wrong area. I think the nodemcu should work fine...

**Comment by pwnmactep** [comment]
Hi,

i made a full dump of my Esp with :
- python esptool.py  --port COM4 read_flash 0x00000 0x400000 full.bin

And checked the Offsets with an Hex Editor ..they should be O.K.

Can you heave a look please ?

Fulldump :
https://www.dropbox.com/s/ifccmb3cxvo5abe/full.bin?dl=0

Here is also a Log File of my ESP working :
https://www.dropbox.com/s/fbhw3q2y247mobh/LOG.txt?dl=0


Thank you for your Time...

**Comment by aczid** [comment]
Here's what happens when I type `make flash`:

    $ make flash
    esptool.py read_flash 0x3c000 0x4000 saved_passwords.bin
    Connecting...
    Please wait...
    esptool.py write_flash 0 esp8266_upc_keys-0x00000.bin 0x40000 esp8266_upc_keys-0x40000.bin 0x3c000 saved_passwords.bin
    Connecting...
    Erasing flash...
    Took 0.63s to erase flash block
    Wrote 35840 bytes at 0x00000000 in 3.5 seconds (82.0 kbit/s)...
    Erasing flash...
    Took 1.60s to erase flash block
    Wrote 186368 bytes at 0x00040000 in 18.2 seconds (81.9 kbit/s)...
    Erasing flash...
    Took 0.26s to erase flash block
    Wrote 16384 bytes at 0x0003c000 in 1.5 seconds (84.7 kbit/s)...
    
    Leaving...

**Comment by aczid** [comment]
I don't know what's going wrong. Your `full.bin` file looks correct. All `0xff` in the 16k range from `0x3c000` to `0x40000`.

**Comment by pwnmactep** [comment]
mkay..can i ask on wich Esp model you work with =? Somehow i think my ESP 12 is the Reason..

**Comment by aczid** [comment]
I use the WeMos D1 mini which has an esp8266...

**Comment by pwnmactep** [comment]
Hi,
your WeMos D1 runns also with an ESP-12e....strange and misterious ;)

Could you "Just for Fun" send me your .bin´s 

- esp8266_upc_keys-0x00000.bin
- esp8266_upc_keys-0x40000.bin
- saved_passwords.bin (clean)

mailto:pwnmactep@gmail.com

Ty! Anyway for your Time and your awesome Job  !

**Comment by aczid** [comment]
Here you go... I'm not sure this is where the problem lies since the rest of the software seems to work fine.
http://s000.tinyupload.com/index.php?file_id=19082954908280126982

**Comment by aczid** [comment]
I recently got a module with the same problem. I guess the flash chip is different...

**Comment by pwnmactep** [comment]
Hi,
good to know..Did you allready got a Fix for it ?

**Comment by aczid** [comment]
Hey man I think this issue was caused by a silly bug of my own. I've tested it on esp8266 devices with 32M and 128M flash chips, both are working fine now. Please check if your issue is resolved too.

**Comment by pwnmactep** [comment]
Hi ,
Works great now ! Thanks for your great Job .
